export const products = [
  // ------------------- Leather Products (categoryId: 1) -------------------
  { id: 1, name: "Leather Bottle A", subCategoryId: 1, price: 4500, material: "Genuine Leather", description: "Rugged leather bottle for daily use.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 2, name: "Leather Bottle B", subCategoryId: 1, price: 4700, material: "Genuine Leather", description: "Stylish leather bottle with premium finish.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 3, name: "Leather Bottle C", subCategoryId: 1, price: 5000, material: "Genuine Leather", description: "Durable leather bottle crafted for endurance.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 4, name: "Leather Bottle D", subCategoryId: 1, price: 4800, material: "Genuine Leather", description: "Classic leather bottle for adventurers.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 5, name: "Leather Bag A", subCategoryId: 2, price: 12000, material: "Premium Leather", description: "Spacious travel bag with sturdy build.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 6, name: "Leather Bag B", subCategoryId: 2, price: 12500, material: "Premium Leather", description: "Elegant leather bag for all occasions.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 7, name: "Leather Bag C", subCategoryId: 2, price: 11800, material: "Premium Leather", description: "Durable leather bag for everyday use.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 8, name: "Leather Bag D", subCategoryId: 2, price: 13000, material: "Premium Leather", description: "Classic design leather travel bag.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 9, name: "Leather Wallet A", subCategoryId: 3, price: 2500, material: "Genuine Leather", description: "Compact and durable leather wallet.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 10, name: "Leather Wallet B", subCategoryId: 3, price: 2700, material: "Genuine Leather", description: "Premium leather wallet with multiple compartments.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 11, name: "Leather Wallet C", subCategoryId: 3, price: 2600, material: "Genuine Leather", description: "Classic wallet crafted for durability.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 12, name: "Leather Wallet D", subCategoryId: 3, price: 2800, material: "Genuine Leather", description: "Elegant leather wallet with smooth finish.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 13, name: "Leather Pouch A", subCategoryId: 4, price: 1800, material: "Genuine Leather", description: "Small leather pouch for essentials.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 14, name: "Leather Pouch B", subCategoryId: 4, price: 1900, material: "Genuine Leather", description: "Durable leather pouch for daily use.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 15, name: "Leather Pouch C", subCategoryId: 4, price: 1850, material: "Genuine Leather", description: "Classic leather pouch with premium finish.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 16, name: "Leather Pouch D", subCategoryId: 4, price: 1950, material: "Genuine Leather", description: "Stylish leather pouch for adventurers.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 17, name: "Leather Belt A", subCategoryId: 5, price: 2200, material: "Genuine Leather", description: "Strong leather belt for everyday wear.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 18, name: "Leather Belt B", subCategoryId: 5, price: 2300, material: "Genuine Leather", description: "Premium leather belt with classic buckle.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 19, name: "Leather Belt C", subCategoryId: 5, price: 2250, material: "Genuine Leather", description: "Stylish and durable leather belt.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 20, name: "Leather Belt D", subCategoryId: 5, price: 2350, material: "Genuine Leather", description: "Elegant leather belt for all occasions.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 21, name: "Leather Holster A", subCategoryId: 6, price: 5500, material: "Premium Leather", description: "Durable leather holster for firearms.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 22, name: "Leather Holster B", subCategoryId: 6, price: 5700, material: "Premium Leather", description: "Classic leather holster with secure fit.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 23, name: "Leather Holster C", subCategoryId: 6, price: 5600, material: "Premium Leather", description: "Stylish and functional leather holster.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 24, name: "Leather Holster D", subCategoryId: 6, price: 5800, material: "Premium Leather", description: "Leather holster crafted for endurance.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  // ------------------- Arms & Protective Gear (categoryId: 2) -------------------
  { id: 25, name: "Arm Guard A", subCategoryId: 7, price: 8000, material: "Reinforced Steel", description: "Protective arm guard for training.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 26, name: "Arm Guard B", subCategoryId: 7, price: 8200, material: "Reinforced Steel", description: "Durable arm guard for combat practice.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 27, name: "Arm Guard C", subCategoryId: 7, price: 8100, material: "Reinforced Steel", description: "Steel arm guard for safety and style.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 28, name: "Arm Guard D", subCategoryId: 7, price: 8300, material: "Reinforced Steel", description: "Premium arm guard for warriors.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 29, name: "Leg Guard A", subCategoryId: 8, price: 9500, material: "Reinforced Steel", description: "Protective leg guard for combat.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 30, name: "Leg Guard B", subCategoryId: 8, price: 9700, material: "Reinforced Steel", description: "Durable leg guard for battle training.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 31, name: "Leg Guard C", subCategoryId: 8, price: 9600, material: "Reinforced Steel", description: "Steel leg guard for warriors.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 32, name: "Leg Guard D", subCategoryId: 8, price: 9800, material: "Reinforced Steel", description: "Premium leg guard for protection.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 33, name: "Sword A", subCategoryId: 9, price: 15000, material: "High-Carbon Steel", description: "Balanced longsword for combat and display.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 34, name: "Sword B", subCategoryId: 9, price: 15200, material: "High-Carbon Steel", description: "Premium sword for collectors.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 35, name: "Sword C", subCategoryId: 9, price: 15500, material: "High-Carbon Steel", description: "Classic sword for martial training.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 36, name: "Sword D", subCategoryId: 9, price: 15800, material: "High-Carbon Steel", description: "Longsword with elegant craftsmanship.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 37, name: "Dagger A", subCategoryId: 10, price: 7000, material: "High-Carbon Steel", description: "Sharp dagger for self-defense.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 38, name: "Dagger B", subCategoryId: 10, price: 7200, material: "High-Carbon Steel", description: "Durable dagger for collection.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 39, name: "Dagger C", subCategoryId: 10, price: 7100, material: "High-Carbon Steel", description: "Compact dagger with protective sheath.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 40, name: "Dagger D", subCategoryId: 10, price: 7300, material: "High-Carbon Steel", description: "Elegant dagger for martial arts practice.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 41, name: "Axe A", subCategoryId: 11, price: 14000, material: "High-Carbon Steel", description: "Sharp axe for display or practice.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 42, name: "Axe B", subCategoryId: 11, price: 14200, material: "High-Carbon Steel", description: "Durable axe for training.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 43, name: "Axe C", subCategoryId: 11, price: 14500, material: "High-Carbon Steel", description: "Premium axe for collectors.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 44, name: "Axe D", subCategoryId: 11, price: 14800, material: "High-Carbon Steel", description: "Classic axe with balanced weight.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 45, name: "Shield A", subCategoryId: 12, price: 12000, material: "Reinforced Steel", description: "Round shield for training and display.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 46, name: "Shield B", subCategoryId: 12, price: 12200, material: "Reinforced Steel", description: "Durable shield for combat practice.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 47, name: "Shield C", subCategoryId: 12, price: 12400, material: "Reinforced Steel", description: "Classic shield for warriors.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 48, name: "Shield D", subCategoryId: 12, price: 12600, material: "Reinforced Steel", description: "Premium steel shield for protection.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 49, name: "Protective Vest A", subCategoryId: 13, price: 25000, material: "Kevlar & Steel", description: "High-protection vest for combat.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 50, name: "Protective Vest B", subCategoryId: 13, price: 25500, material: "Kevlar & Steel", description: "Durable vest for safety and training.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 51, name: "Protective Vest C", subCategoryId: 13, price: 26000, material: "Kevlar & Steel", description: "Premium protective vest for warriors.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "amber-700" },
  { id: 52, name: "Protective Vest D", subCategoryId: 13, price: 26500, material: "Kevlar & Steel", description: "High-end protective vest for professionals.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },

  { id: 53, name: "Bow & Arrow Accessories A", subCategoryId: 14, price: 6000, material: "Wood & Steel", description: "Essential bow & arrow accessory set.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 54, name: "Bow & Arrow Accessories B", subCategoryId: 14, price: 6200, material: "Wood & Steel", description: "Durable accessory set for archery.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 55, name: "Bow & Arrow Accessories C", subCategoryId: 14, price: 6100, material: "Wood & Steel", description: "Premium accessory set for precision.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
  { id: 56, name: "Bow & Arrow Accessories D", subCategoryId: 14, price: 6300, material: "Wood & Steel", description: "Classic archery accessory set.", images: ["https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s"], thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZLjLNDDMnDhUIkaREiVJInlu8EdMlZoWVIQ&s" },
];
